name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build . --target test -t todo-app:test 
    - run: docker run --env-file ./.env.test todo-app:test
 
  dockerhub:
    name: Build Image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == 'exercise-12'
    steps:
    - run: echo "Publishing!!" 
    - uses: actions/checkout@v2

    - name: Docker Build
      run: docker build -t rubydoma/todo-app-exercise-8 .

    - name: Login
      run: echo ${{secrets.DOCKERHUBTOKEN}} | docker login --username rubydoma --password-stdin
      
    - name: Push Image to Docker Hub
      run: docker push rubydoma/todo-app-exercise-8

  provision:
    name: creating infrastructure
    runs-on: ubuntu-latest
    needs: dockerhub
    steps:
    - uses: actions/checkout@v2
    - name: terraform init 
      run: terraform init 
      env:
        ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
        ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
        ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
        ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
        ARM_ACCESS_KEY: ${{secrets.ARM_ACCESS_KEY}}
    - name: terraform apply
      run: terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
        ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
        ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
        ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
        ARM_ACCESS_KEY: ${{secrets.ARM_ACCESS_KEY}}
        TF_VAR_clientid: ${{secrets.CLIENT_ID}}
        TF_VAR_clientsecret: ${{secrets.CLIENT_SECRET}}
    - name: Deploy the latest version of the image
      run: |
        curl -dH -X POST "$(terraform output -raw webhook)"
      env: 
        ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
        ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
        ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
        ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
        ARM_ACCESS_KEY: ${{secrets.ARM_ACCESS_KEY}}



    

      

 

    