name: Continuous Integration
on: [push]
jobs:
  build:
    dockerfile: Dockerfile
      context: .
      target: test
    volumes:
      - type: bind
        source: ./todo_app
        target: /opt/todo_app

   
      