name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run:
      - webapp-test:
          container_name: test
          build:
            dockerfile: Dockerfile
            context: .
            target: test
          volumes:
            - type: bind
              source: ./todo_app
              target: /opt/todo_app
   


   
  

    